/**
 * Generates demo/example-fleet-nottingham-matrix.txt from real coordinates.
 *
 * The fixture is a DERIVED artifact and this script is its source. That matters
 * because the first version of the matrix was produced by an ad-hoc calculation
 * that was not kept, and it turned out not to be reproducible from any single
 * set of coordinates — two cells were 0.1 min away from what the geometry
 * actually gives. A published benchmark that cannot be regenerated is not a
 * benchmark, so the generator is now in the repository and CI checks the
 * committed matrix still matches it.
 *
 * Run:  node tools/fixture/nottingham.mjs          (writes the matrix)
 *       node tools/fixture/nottingham.mjs --check  (fails if it is stale)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT = join(ROOT, 'demo/example-fleet-nottingham-matrix.txt');
const CSV = join(ROOT, 'demo/example-fleet-nottingham.csv');

/* The round as a planner would hand it over: stops in ALPHABETICAL order.
   That is not a strawman. A depot that keeps its stop list in a spreadsheet
   sorted by name, or that exports from a CRM in name order, produces exactly
   this, and it is one of the commonest avoidable failures in the field. */
export const VEHICLE = 'VAN-21';
export const DEPART_MINS = 540;   // 09:00
export const WINDOW_OPEN = 480;   // 08:00
export const WINDOW_CLOSE = 615;  // 10:15
/** Interior stops, alphabetical, which is how the sheet arrives. */
export const SHEET_ORDER = [1, 2, 3, 4, 5];

/* WGS84 locality centroids, Nottingham and its suburbs, 4 decimal places
   (~11 m). Node 0 is the depot: Nottingham city centre. See
   docs/FIXTURE-NOTTINGHAM.md for why each is where it is. */
export const NODES = [
  ['DEPOT',    52.9548, -1.1581],
  ['Arnold',   53.0050, -1.1270],
  ['Beeston',  52.9270, -1.2130],
  ['Bulwell',  52.9987, -1.1953],
  ['Carlton',  52.9668, -1.0913],
  ['Chilwell', 52.9167, -1.2332],
];

/** IUGG mean Earth radius, km. */
export const EARTH_RADIUS_KM = 6371.0088;
/** Fixed urban average speed, km/h. Documented, not fitted. */
export const SPEED_KMH = 30;

const rad = (d) => (d * Math.PI) / 180;

/** Great-circle distance in km between two [lat, lon] pairs. */
export function haversineKm(a, b) {
  const dLat = rad(b[0] - a[0]);
  const dLon = rad(b[1] - a[1]);
  const s =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(rad(a[0])) * Math.cos(rad(b[0])) * Math.sin(dLon / 2) ** 2;
  return 2 * EARTH_RADIUS_KM * Math.asin(Math.sqrt(s));
}

/**
 * The matrix, in minutes rounded to one decimal place.
 *
 * One decimal place is not a display choice — it is the value. Q16.16 can hold
 * 0.1 only to within 1/65536, so the number that gets hashed must be the same
 * decimal string everywhere, and rounding once, here, at generation time, is
 * what makes that true. Everything downstream reads the rounded value.
 */
export function matrixMinutes() {
  const n = NODES.length;
  const m = [];
  for (let i = 0; i < n; i++) {
    const row = [];
    for (let j = 0; j < n; j++) {
      const km = haversineKm(NODES[i].slice(1), NODES[j].slice(1));
      row.push(Number(((km / SPEED_KMH) * 60).toFixed(1)));
    }
    m.push(row);
  }
  return m;
}

/** The alphabetical round as node ids, depot-pinned at both ends. */
export function sheetRoute() {
  return [0, ...SHEET_ORDER, 0];
}

function renderCsv() {
  const m = matrixMinutes();
  const route = sheetRoute();
  const rows = [['vehicle', 'seq', 'stop', 'window_open', 'window_close',
                 'travel_mins_from_previous', 'depart'].join(',')];
  route.forEach((node, seq) => {
    const depot = node === 0;
    const travel = seq === 0 ? 0 : m[route[seq - 1]][node];
    rows.push([
      VEHICLE, seq, NODES[node][0],
      depot ? 0 : WINDOW_OPEN,
      depot ? 1440 : WINDOW_CLOSE,
      travel.toFixed(1), DEPART_MINS,
    ].join(','));
  });
  return rows.join('\n') + '\n';
}

function render() {
  const m = matrixMinutes();
  const legend = NODES.map((nd, i) => `${i}=${nd[0]}`).join(', ');
  return [
    '# Lattice117 distance matrix - minutes, Q16.16-safe to 1 dp',
    '# Derived from WGS84 locality centroids by Haversine great-circle',
    `# distance at a fixed ${SPEED_KMH} km/h urban average. Straight-line, NOT road`,
    '# distance: see docs/FIXTURE-NOTTINGHAM.md for the coordinates and the',
    '# reasons this is a demonstration fixture and not a routing product.',
    '#',
    '# GENERATED by tools/fixture/nottingham.mjs - do not hand-edit. Regenerate',
    '# with `node tools/fixture/nottingham.mjs`; CI checks it is not stale.',
    `# nodes: ${legend}`,
    ...m.map((r) => r.map((v) => v.toFixed(1)).join(' ')),
    '',
  ].join('\n');
}

const artifacts = [[OUT, render()], [CSV, renderCsv()]];

if (process.argv.includes('--check')) {
  let stale = [];
  for (const [path, want] of artifacts) {
    let have = '';
    try { have = readFileSync(path, 'utf8'); } catch { /* missing counts as stale */ }
    if (have.replace(/\r\n/g, '\n') !== want) stale.push(path);
  }
  if (stale.length) {
    console.error(`stale, run node tools/fixture/nottingham.mjs:\n  ${stale.join('\n  ')}`);
    process.exit(1);
  }
  console.log('Nottingham fixture is up to date');
} else if (process.argv[1] && process.argv[1].endsWith('nottingham.mjs')) {
  for (const [path, want] of artifacts) {
    writeFileSync(path, want);
    console.log(`wrote ${path}`);
  }
}
