/**
 * Render the store assets from the real product surfaces.
 *
 * Honesty rules this harness follows, because store screenshots are
 * representations and a fabricated one is a misrepresentation:
 *
 *   - Every panel shown is the real page, loaded live in an iframe, driven by
 *     the repository's own fixtures. Nothing is mocked up in a design tool.
 *   - The verdicts, digests and counts on screen are computed at capture time
 *     by the same WASM engine the product ships.
 *   - Nothing imitates Excel or Google Sheets chrome. These are product shots
 *     of the add-in's own pane, not composites pretending to be inside a host
 *     application. See README.md for why that matters for submission.
 *
 * Usage:  node tools/store-assets/capture.mjs
 */
import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
import { mkdirSync, existsSync, readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..', '..');
const OUT_MS = join(REPO, 'store-assets', 'appsource');
const OUT_G  = join(REPO, 'store-assets', 'workspace');
const PORT = 8749;
const BASE = `http://127.0.0.1:${PORT}`;
const EXE = process.env.CHROMIUM_PATH || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome';

mkdirSync(OUT_MS, { recursive: true });
mkdirSync(OUT_G,  { recursive: true });

/* Store screenshots must show the product, not the paywall. On the free tier the
   pane reads "100% rounds achievable" having checked 1 of 8, greys out the
   certificate button and masks the digest — an accurate screenshot of a
   misleading-looking state, and exactly what AppSource reviewers flag as a
   fault. So the capture runs Pro.

   The licence is minted here, at capture time, from licence/keypair.json. That
   file holds the PRIVATE key and is gitignored, so no key is committed and the
   screenshots cannot be regenerated by anyone who should not be able to mint
   licences. Without it, the capture still runs and says what it produced. */
let LICENCE = null;
const KEYPAIR = join(REPO, 'licence', 'keypair.json');
if (existsSync(KEYPAIR)) {
  try {
    LICENCE = execFileSync(process.execPath,
      ['issue.mjs', 'issue', 'store-screenshots@lattice117.local', 'pro', '12'],
      { cwd: join(REPO, 'licence'), encoding: 'utf8' }).trim().split(/\s+/).pop();
    console.log('Pro licence minted for the capture (not committed).');
  } catch (e) {
    console.log('Could not mint a licence:', e.message);
  }
} else {
  console.log('WARNING: licence/keypair.json absent — capturing the FREE tier.');
  console.log('         The shots will show the free-tier cap and a masked digest.');
}

/* The rota fixture, as getDisplayValues() would hand it over. */
const ROTA_ROWS = readFileSync(join(REPO, 'demo', 'example-rota.csv'), 'utf8')
  .trim().split(/\r?\n/).map((l) => l.split(','));

const srv = spawn('python3', ['-m', 'http.server', String(PORT), '-d', REPO], { stdio: 'ignore' });
await new Promise((r) => setTimeout(r, 1300));

const browser = await chromium.launch({ executablePath: EXE });
const problems = [];

/* The two host APIs the panes expect. Stubbed only far enough for the page to
   render its own UI; nothing here supplies data or fakes a result. */
const HOST_STUBS = `
  window.Office = {
    onReady: (cb) => cb({ host: 'Excel', platform: 'PC' }),
    HostType: { Excel: 'Excel' },
  };
  /* readSelection() returns getDisplayValues() — a 2-D array of the strings the
     user sees. The stub hands back the repository's own rota fixture in exactly
     that shape, so the sidebar evaluates real data with the real engine and the
     digest on screen is the one the white paper cites. Nothing is faked past
     the host boundary. */
  window.__L117_ROWS__ = ROWS_JSON;
  window.google = { script: { run: (function () {
    const api = {
      withSuccessHandler(cb) { api._ok = cb; return api; },
      withFailureHandler(cb) { api._fail = cb; return api; },
      readSelection() { setTimeout(() => api._ok && api._ok(window.__L117_ROWS__), 60); },
      highlightRows() {}, clearHighlighting() {},
    };
    return api;
  })() } };
`;

const frame = (opts) => {
  const p = new URLSearchParams(opts);
  return `${BASE}/tools/store-assets/frame.html?${p}`;
};

async function shoot({ name, url, dir, width, height, prepare, waitFor }) {
  const ctx = await browser.newContext({
    viewport: { width, height }, deviceScaleFactor: 1,
  });
  await ctx.addInitScript(HOST_STUBS.replace('ROWS_JSON', JSON.stringify(ROTA_ROWS)));
  if (LICENCE) {
    await ctx.addInitScript((key) => {
      try { localStorage.setItem('lattice117.licence', key); } catch { /* blocked */ }
    }, LICENCE);
  }
  const page = await ctx.newPage();
  const errs = [];
  page.on('pageerror', (e) => errs.push(e.message));
  page.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()); });
  page.on('response', (r) => {
    if (r.status() === 404 && !/favicon/i.test(r.url())) errs.push(`404 ${r.url()}`);
  });

  await page.goto(url, { waitUntil: 'networkidle' });
  if (prepare) await prepare(page);
  if (waitFor) {
    try { await waitFor(page); }
    catch (e) { problems.push(`${name}: ${e.message}`); }
  }
  await page.waitForTimeout(700);

  const file = join(dir, name);
  await page.screenshot({ path: file });
  const real = errs.filter((e) =>
    !/office\.js|Office is not defined|favicon/i.test(e) &&
    !/Failed to load resource/i.test(e));   // the 404 listener reports the URL instead
  console.log(`  ${name.padEnd(34)} ${width}x${height}` + (real.length ? `  ERRORS: ${real[0]}` : ''));
  if (real.length) problems.push(`${name}: ${real[0]}`);
  await ctx.close();
}

/* Drive the browser page inside the frame's iframe, using its own buttons. */
const inFrame = (fn) => async (page) => {
  const f = page.frames().find((x) => x !== page.mainFrame());
  if (!f) throw new Error('iframe never attached');
  await fn(f);
};

/* The page hides the inactive tab's panel, so its buttons are present but not
   clickable. Select the tab first — the same way a user would. */
async function openTab(f, tab) {
  await f.click(`.tab[data-tab="${tab}"]`, { timeout: 15000 });
  await f.waitForTimeout(400);
}

/* The real user flow, which is three steps and not one: pick the tab, load the
   example, then confirm the column mapping. #runCsv is shared between modes and
   relabels itself ("Audit this sheet" / "Check this rota").

   The loader buttons start disabled and are enabled once the WASM module is
   ready, so this waits on that rather than sleeping and hoping. */
async function loadFixture(f, tab, loadButton, readyPanel) {
  await openTab(f, tab);
  await f.waitForSelector(`${loadButton}:not([disabled])`, { timeout: 25000 });
  await f.click(loadButton);
  await f.waitForSelector('#mapper', { state: 'visible', timeout: 15000 });
  await f.waitForTimeout(350);
  await f.click('#runCsv');
  // Fleet verdicts render into #resultPanel, rota into #rotaPanel.
  await f.waitForSelector(readyPanel, { state: 'visible', timeout: 20000 });
  await f.waitForTimeout(900);
}

console.log('\nAppSource — 1366x768');

await shoot({
  name: '01-fleet-result.png', dir: OUT_MS, width: 1366, height: 768,
  url: frame({
    src: `${BASE}/demo/audit.html`, w: 452, h: 648,
    head: 'Does the round <em>actually hold</em>?',
    sub: 'Checks every stop against its own time window and names the first one that breaks — the stop, the arrival, the window close and the deficit, in minutes.',
    tags: 'Runs offline|No upload|Fixed-point integers|Names the exact stop',
  }),
  prepare: inFrame(async (f) => {
    await loadFixture(f, 'csv', '#loadExCsv', '#resultPanel');
    await f.evaluate(() => {
      const el = document.getElementById('resultPanel');
      if (el) window.scrollTo({ top: el.getBoundingClientRect().top + window.scrollY - 14 });
    });
  }),
});

await shoot({
  name: '02-fleet-violation-detail.png', dir: OUT_MS, width: 1366, height: 768,
  url: frame({
    src: `${BASE}/demo/audit.html`, w: 452, h: 648,
    eyebrow: 'Names the failure',
    head: 'Not “infeasible”. <em>Which stop, and by how much.</em>',
    sub: 'Every quantity is a Q16.16 fixed-point integer, so the deficit is exact and the same on any machine that runs it.',
    tags: 'Exact arithmetic|No floating point|Reproducible verdict',
  }),
  prepare: inFrame(async (f) => {
    await loadFixture(f, 'csv', '#loadExCsv', '#resultPanel');
    await f.evaluate(() => {
      const v = document.getElementById('violPanel');
      const t = (v && v.offsetParent !== null) ? v : document.getElementById('resultPanel');
      if (t) window.scrollTo({ top: t.getBoundingClientRect().top + window.scrollY - 14 });
    });
  }),
});

await shoot({
  name: '03-rota-result.png', dir: OUT_MS, width: 1366, height: 768,
  url: frame({
    src: `${BASE}/demo/audit.html?mode=rota`, w: 556, h: 648,
    eyebrow: 'UK rest & break check',
    head: 'Rest and break checks, <em>row by row</em>.',
    sub: 'Indicative check against configured rules — 11h inter-shift rest, 20m break over 6h. Not legal advice, and it says so on screen.',
    tags: 'One row per shift|Night shifts handled|Shortfall in minutes',
  }),
  prepare: inFrame(async (f) => {
    await loadFixture(f, 'rota', '#loadExRota', '#rotaPanel');
    await f.evaluate(() => {
      const p = document.getElementById('rotaPanel');
      if (p) window.scrollTo({ top: p.getBoundingClientRect().top + window.scrollY - 14 });
    });
  }),
});

await shoot({
  name: '04-rota-shortfall-detail.png', dir: OUT_MS, width: 1366, height: 768,
  url: frame({
    src: `${BASE}/demo/audit.html?mode=rota`, w: 556, h: 648,
    eyebrow: 'Says what is short',
    head: 'The staff member, the rest achieved, <em>the shortfall</em>.',
    sub: 'A flag is a prompt to look, never a ruling. The check knows nothing of opt-outs, shift-change exceptions or collective agreements, and the pane says so.',
    tags: 'Names the person|Actual vs expected|Disclosed limits',
  }),
  prepare: inFrame(async (f) => {
    await loadFixture(f, 'rota', '#loadExRota', '#rotaPanel');
    await f.evaluate(() => {
      const p = document.getElementById('rotaPanel');
      if (p) window.scrollTo({ top: p.getBoundingClientRect().top + window.scrollY - 14 });
    });
  }),
});

await shoot({
  name: '05-licence-and-privacy.png', dir: OUT_MS, width: 1366, height: 768,
  url: frame({
    src: `${BASE}/demo/audit.html?mode=rota`, w: 500, h: 648,
    eyebrow: 'No account, no server',
    head: 'A licence key you paste. <em>Nothing leaves the machine.</em>',
    sub: 'The key is checked in the browser against a public key. There is no account to create, no server to call, and no telemetry — the add-in opens no sockets at all.',
    tags: 'Offline verification|No telemetry|No sign-up',
  }),
  prepare: inFrame(async (f) => {
    await f.evaluate(() => {
      const box = document.getElementById('licencePanel');
      if (box) window.scrollTo({ top: box.getBoundingClientRect().top + window.scrollY - 14 });
    });
  }),
});

console.log('\nGoogle Workspace');

await shoot({
  name: 'screenshot-1280x800.png', dir: OUT_G, width: 1280, height: 800,
  url: frame({
    src: `${BASE}/sheets-addon/Sidebar.html`, w: 420, h: 660,
    eyebrow: 'Google Sheets add-on',
    head: 'Check a rota <em>without it leaving the sheet</em>.',
    sub: 'One permission: the spreadsheet you have open. No Drive access, no network calls, no data collection. The engine is a 21 KB WebAssembly module in the sidebar.',
    tags: 'spreadsheets.currentonly|No Drive access|21 KB engine',
  }),
  prepare: inFrame(async (f) => {
    // #run relabels itself per mode ("Check selected rows" / "…shifts"), so
    // target the id, and wait for the engine to enable it.
    await f.click('#modeRota', { timeout: 15000 });
    await f.waitForTimeout(250);
    await f.waitForSelector('#run:not([disabled])', { timeout: 25000 });
    await f.click('#run');
    await f.waitForTimeout(2200);
  }),
});

await shoot({ name: 'icon-128.png', dir: OUT_G, width: 128, height: 128,
  url: `${BASE}/tools/store-assets/brand.html?a=icon` });
await shoot({ name: 'promo-220x140.png', dir: OUT_G, width: 220, height: 140,
  url: `${BASE}/tools/store-assets/brand.html?a=promo` });

await browser.close();
srv.kill();

if (problems.length) {
  console.log('\nProblems:');
  for (const p of problems) console.log('  -', p);
  process.exitCode = 1;
} else {
  console.log('\nAll assets captured cleanly.');
}
